### ISSUE TITLE
Debugger not working - using Chrome browser

### ISSUE THREAD

**Issue by tpodom** [mbolotov/intellij-cypress#18]
I have an issue using Chrome with Cypress because my Chrome browse is managed by my organization and I believe Cypress fails to set the proxy properly.  As a result, I normally run Cypress with Electron but when I try to set the run configuration to use Electron the debug action seems to override that with Chrome and then the app never loads.

**Comment by mbolotov** [comment]
Hi @tpodom!
Yes, this is a known issue. The plugin uses Chrome Debug Tools to make a connection to the browser.
It seems that Electron cannot be supported because it requires to pass '--inspect=[port]' command line argument to enable CDT but Cypress can't pass arguments for Electron. See [here](https://docs.cypress.io/api/plugins/browser-launch-api.html#Syntax) for details.

So closing it as won't fix.
