### ISSUE TITLE
Browsers support for debug

### ISSUE THREAD

**Issue by patrick-mota** [mbolotov/intellij-cypress#34]
First of all, thank you for the amazing plugin.

I'm looking forward to get the pro version for my company but for the moment you seems using only chrome for debug.

Are you planning to add support for more browsers ?

Can we help you to do that ?

It would be awesome to have the new edge chromium added (should work out of box since almost all chrome extensions works already with edge) and firefox too.

**Comment by mbolotov** [comment]
Hi @patrick-mota!
Thanks for the evaluation of the plugin! 
I stopped with Chrome only because I thought the debug is mostly needed to see what happening with complex test code that should be working equally in all browsers.

I will try to add debug support for chromium based browsers. But I'm sure about Firefox.

**Comment by patrick-mota** [comment]
So, I'm waiting for your feedback about your try.

Thank you very much for the fast answer !

**Comment by mbolotov** [comment]
I'm uploaded 1.7 version with debug support for Electron and Edge. It will be accessible once Jetbrains approves it (~ 2 days)
Support for Firefox seems to be a hard thing to implement.
Moreover, the [IntelliJ platform itself does not support source mappings for Firefox](https://www.jetbrains.com/help/webstorm/debugging-javascript-in-firefox.html), so it would be not so convenient even if I got Firefox connected on top of Cypress.
