### ISSUE TITLE
cypress.json global overried

### ISSUE THREAD

**Issue by didlika** [mbolotov/intellij-cypress#49]
Is it possible to add option to override on global level for all tests config file? For example I would rather use cypress-acc.json for all tests instead of cypress.json?

**Comment by mbolotov** [comment]
Yes, I think this is possible. 
I will consider to add it to the next 'pro' plugin release.

**Comment by didlika** [comment]
Or even better globally set which tests should use which config files (for example integration tests use one config file, smoke tests use different one). Of course if you decide to decide to add it.

**Comment by mbolotov** [comment]
Well, it may be better to use different folders for each of test type. So the concrete type has it's own config file with a normal `cypress.json` name. Do you consider this case?

By the way, you can run a test from IDE using a non standard file name using the `config-file` CLI argument:
![image](https://user-images.githubusercontent.com/19785715/123068810-e750c300-d41a-11eb-9070-7c2492ba3bdb.png)

You can also define a template config with the argument to force IDE to create any cypress run config with this setting predefined. 

So this issue is mostly about making IDE itself aware of a custom config file name rather than the ability to run a test with such a config.

**Comment by didlika** [comment]
The issue I have is that when i press play button to run single test from test class, it will always call default cypress.json
I would like to set up different cypress.json files for different tests or folders so I can just run test that I want directly from class without having to modify settings each time for each test

**Comment by mbolotov** [comment]
As I said before, you currently have 2 options:
1. Use different folder structures (the fully independent folder structure with all the utils etc. code) with a standard config file name. When you create a run config, the IDE automatically set the current directory in which your test is placed. So when it's run, Cypress will get the correct config name. The drawback of this way may be the need to duplicate/share some util code.
2. Create a template config with a custom config file name. Please note in this case the plugin itself in the current version will still use the common config file name to calculate the context. For example, the plugin uses config data to find out the 'integration folder' setting to check whether this test may be run or not. If a test is not placed inside the 'integration folder' the IDE will not show a gutter to run it.

**Comment by mbolotov** [comment]
As of 2.5.0 version, the plugin allows setting the configuration file path within the system settings:
![image](https://user-images.githubusercontent.com/19785715/135405432-190ecb4c-f444-4628-b10c-a4c4521fc957.png)
